# Generated by Django 3.1.3 on 2020-11-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OCapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='contacto',
            field=models.CharField(max_length=50),
        ),
    ]
