# Generated by Django 3.1.3 on 2020-11-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OCapp', '0002_auto_20201120_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Cuit',
            },
        ),
        migrations.AddField(
            model_name='orden',
            name='descripcion',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='presupuesto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='total',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='contacto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='creado',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='orden',
            name='empresa',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='sectores',
            field=models.ManyToManyField(blank=True, null=True, to='OCapp.Sector'),
        ),
        migrations.AddField(
            model_name='orden',
            name='cuit',
            field=models.ManyToManyField(null=True, to='OCapp.Cuit'),
        ),
    ]
