# Generated by Django 3.1.3 on 2020-11-20 23:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('OCapp', '0003_auto_20201120_1943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuit',
            options={'verbose_name': 'Cuit', 'verbose_name_plural': 'cuits'},
        ),
        migrations.AddField(
            model_name='cuit',
            name='actualizado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuit',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orden',
            name='cuit',
            field=models.ManyToManyField(to='OCapp.Cuit'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='sectores',
            field=models.ManyToManyField(to='OCapp.Sector'),
        ),
    ]
